security:
  oauth2:
    client:
      clientId: account-service
      #clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      clientSecret: ABC123
      #accessTokenUri: http://auth-service:5000/uaa/oauth/token
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: localhost
      #username: user
      #password: ${MONGODB_PASSWORD}
      database: account
      port: 27017

server:
  context-path: /accounts
  port: 6000
