spring:
   profiles.active: dev

server:
  context-path: /accounts
  port: 6000
  
---
spring:
  profiles: local
  data:
    mongodb:
      host: 10.220.42.26
      database: piggymetrics
      port: 26000
      username: user
      password: ABC123

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ABC123
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

---
spring:
  profiles: dev
  data:
    mongodb:
      host: 10.220.42.26
      database: piggymetrics
      port: 26000
      username: user
      password: ABC123

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ABC123
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

---
spring:
  profiles: docker
  data:
    mongodb:
      host: account-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
  