spring:
   profiles.active: dev

server:
  context-path: /uaa
  port: 5000
  
---
spring:
  profiles: local

  data:
    mongodb:
      host: 10.220.42.26
      port: 25000
      database: piggymetrics
      username: user
      password: ABC123
      
---
spring:
  profiles: dev

  data:
    mongodb:
      host: 10.220.42.26
      port: 25000
      database: piggymetrics
      username: user
      password: ABC123

---
spring:
  profiles: docker

  data:
    mongodb:
      host: auth-mongodb
      port: 27017
      database: piggymetrics
      username: user
      password: ${MONGODB_PASSWORD}
      