spring:
   profiles.active: dev

server:
  context-path: /statistics
  port: 7000

rates:
  url: http://api.fixer.io

---

spring:
  profiles: local
  data:
    mongodb:
      host: 10.220.42.26
      port: 27000
      database: piggymetrics
      username: user
      password: ABC123

security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ABC123
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

---
spring:
  profiles: dev
  data:
    mongodb:
      host: 10.220.42.26
      port: 27000
      database: piggymetrics
      username: user
      password: ABC123

security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ABC123
      accessTokenUri: http://10.220.42.26:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

---

spring:
  profiles: docker
  data:
    mongodb:
      host: statistics-mongodb
      port: 27000
      database: piggymetrics
      username: user
      password: ${MONGODB_PASSWORD}

security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
